### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by epac-tom** [Yohannfra/nrf_sdk_sdkconfig_diff#1]
$ python compare_sdkconfig.py examples/sdk_config_1.h examples/sdk_config_2.h
```
Traceback (most recent call last):
  File "D:\code\nrf_sdk_sdkconfig_diff\compare_sdkconfig.py", line 63, in <module>
    main(len(sys.argv), sys.argv)
  File "D:\code\nrf_sdk_sdkconfig_diff\compare_sdkconfig.py", line 60, in main
    print(tabulate(table, headers='firstrow', tablefmt='fancy_grid'))
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-77: character maps to <undefined>
```

**Comment by Yohannfra** [comment]
Hi, I can't reproduce this crash, it works as expected on my machine, but after a quick google I maybe found the issue and just pushed a commit to fix it. Can you try again with the latest master version ?

Thanks

**Comment by epac-tom** [comment]
@Yohannfra thanks for the quick response!
I pulled the change but still get the same response.

I'm running python 3.10.4 on Windows 10 64 bit, is there any other info I could provide?

**Comment by Yohannfra** [comment]
What version of tabulate do you have ? 


```
$ python3
Python 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tabulate
>>> tabulate.__version__
'0.8.10'
```

**Comment by epac-tom** [comment]
0.8.10
From the downvoted answer on [stackoverflow](https://stackoverflow.com/a/63199767/18962763), I tried encoding='iso-8859-1'  and it sprung into life

**Comment by Yohannfra** [comment]
Or try as said in [this discussion](https://github.com/llSourcell/twitter_sentiment_challenge/issues/1)

run chcp 65001 at first.

1.```chcp 65001```
2.```python compare_sdkconfig.py examples/sdk_config_1.h examples/sdk_config_2.h```

**Comment by epac-tom** [comment]
Just realised, I should have mentioned I was using git bash rather than command prompt.
Using command prompt they all work, including without the encoding option.

**Comment by Yohannfra** [comment]
Ok, thanks for letting me know about this issue, I don't think I'll do anything to fix it if it's just a git-bash related issue but i'll document this in README for futur users.
